export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpeg",
    username: "Asep Sumanji",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Ilham Kurniawan",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Dadang Surdadang",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Dora The Explorer",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpeg",
    username: "Thomas Slebew",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Kylian Bapake",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Cristiano Romadhon",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Kristen Islam",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Timoty Nolan",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Gan An Wo",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum maximus nec nunc ac euismod. Suspendisse ut lacinia urna. Suspendisse lacus magna, aliquam in turpis non, lobortis sagittis tellus. Proin innunc ac euismod. Suspendisse ut lacinia urna. Suspendisse lacus magna, aliquam in turpis non, lobortis sagittis tellus. Proin in", 
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam a est risus. Ut mi est, mattis a vestibulum eu, fermentum viverra dui. Vestibulum auctor mollis consequat. Aliquam erat volutpat. Mauris lobortis feugiat semper. Vivamus sodales risus sit amet volutpat consectetur. Duis non sollicitudin leo. Fusce pharetra rhoncus luctus. Maecenas orci.",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
